name: Test Minigeth

on: [push, pull_request]

jobs:
  unit:
    name: minigeth computes correct block transitions
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        submodules: true
    - name: Install Toolchain
      run: |
        sudo apt-get update
        sudo apt-get -y --no-install-recommends install golang-1.16 make cmake pkg-config
    - name: Build minigeth
      run: make minigeth_prefetch
    - name: Test Minigeth
      run: make test_minigeth
