name: Test Challenge

on: [push, pull_request]

jobs:
  unit:
    name: Challenge on block 13284469
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        submodules: true
    - name: Install Toolchain (Go, Node.js, Yarn and Make)
      run: |
        sudo apt-get update
        sudo apt-get -y --no-install-recommends install golang-1.16 nodejs npm make
        npm install --global yarn
    - name: Build
      run: make unicorn minigeth_mips minigeth_default_arch mipsevm yarn
    - name: Run test challenge
      run: make test_challenge
