name: Test Challenge Fault

on: pull_request

jobs:
  unit:
    name: Fault injection challenge scenario
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        submodules: true
    - name: Install Toolchain
      run: |
        sudo apt-get update
        sudo apt-get -y --no-install-recommends install golang-1.17 nodejs make cmake pkg-config
        npm install --global pnpm
    - name: Build
      run: make build
    - name: Run fault injection challenge scenario
      run: demo/challenge_fault.sh
